################################################################################
################################## brew tap ####################################
################################################################################

tap "homebrew/bundle"
# tap "homebrew/cask-fonts"

################################################################################
################################ brew install ##################################
################################################################################

# AWS Packages
brew "awscli"
brew "aws-iam-authenticator"
brew "eksctl"

# Azure Packages
brew "azure-cli"

# HashiCorp / OpenTofu
brew "vault"
brew "opentofu"

# Git packages
brew "pre-commit"

# Go Packages
brew "go"
brew "golangci-lint"

# JavaScript Packages
brew "node"
brew "nvm"

# Python Packages
brew "python@3.11"
brew "virtualenv"
brew "pyenv"
brew "pipenv"

# Java Packages
brew "openjdk"
brew "gradle"

# Ruby Packages
brew "ruby"
brew "ruby-install"

# K8s Packages
brew "kubernetes-cli"
brew "hadolint"
brew "helm"
brew "istioctl"
brew "minikube"

# Networking & Security Packages
brew "websocat"
brew "openssl@1.1"
brew "openssl@3"

# Database Packages
brew "mongosh"
brew "postgresql@14"

# General Tooling
brew "tree"
brew "wget"
# Ansible is installed by the bootstrap.sh script, though needs to remain here
# due to the brew bundle cleanup task, which will remove Ansible if it's not
# listed here.
brew "ansible"
brew "libyaml"
brew "yamllint"
brew "ansible-lint"
brew "argo"
brew "automake"
brew "bison"
brew "chruby"
brew "docutils"
brew "gdbm"
brew "jq"
brew "libffi"
brew "librdkafka"
brew "mkcert"
brew "nmap"

################################################################################
################################## brew cask ###################################
################################################################################

# Networking
cask "wireshark"
# cask "aws-vpn-client"
# cask openvpn-connect
# cask microsoft-remote-desktop

# Messengers
# cask "slack"
# cask "microsoft-teams"
cask "discord"
cask "whatsapp"
# cask "messenger"
# cask "signal"
# cask zoom

# Terminal & IDE
cask "iterm2"
cask "visual-studio-code"
cask "font-fira-code"
cask "powershell"

# Media & Gaming
cask "spotify"
# cask sony-ps-remote-play
# cask steam

# Containers
cask "docker"

# Genral Tooling
cask "keepingyouawake"
cask "postman"
# cask "the-unarchiver"
# cask google-chrome
# cask nordpass

################################################################################
############################### vscode extensions ##############################
################################################################################

vscode "amazonwebservices.amazon-q-vscode"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "antfu.icons-carbon"
vscode "dbaeumer.vscode-eslint"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "eriklynd.json-tools"
vscode "esbenp.prettier-vscode"
vscode "golang.go"
vscode "ivory-lab.jenkinsfile-support"
vscode "miguelsolorio.fluent-icons"
vscode "mongodb.mongodb-vscode"
vscode "ms-azure-devops.azure-pipelines"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "njpwerner.autodocstring"
vscode "pkief.material-icon-theme"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
vscode "tim-koehler.helm-intellisense"
vscode "yzhang.markdown-all-in-one"
vscode "streetsidesoftware.code-spell-checker"
