# brew tap
tap "homebrew/bundle"
# tap "homebrew/cask-fonts"

# brew install
brew "openssl@3"
brew "libyaml"
# Ansible is installed by the bootstrap.sh script, though needs to remain here
# due to the brew bundle cleanup task, which will remove Ansible if it's not
# listed here.
brew "ansible"
brew "yamllint"
brew "ansible-lint"
brew "argo"
brew "automake"
brew "node"
brew "aws-iam-authenticator"
brew "python@3.11"
brew "awscli"
brew "azure-cli"
brew "bison"
brew "chruby"
brew "docutils"
brew "eksctl"
brew "gdbm"
brew "go"
brew "golangci-lint"
brew "hadolint"
brew "helm"
brew "istioctl"
brew "jq"
brew "kubernetes-cli"
brew "libffi"
brew "librdkafka"
brew "minikube"
brew "mkcert"
brew "mongosh"
brew "nmap"
brew "nvm"
brew "openssl@1.1"
brew "opentofu"
brew "openjdk"
brew "virtualenv"
brew "pipenv"
brew "postgresql@14"
brew "pre-commit"
brew "pyenv"
brew "python@3.10"
brew "ruby"
brew "ruby-install"
brew "sslscan"
brew "tree"
brew "vault"
brew "websocat"
brew "wget"

# brew install --cask

# Networking
cask "wireshark"
# cask "aws-vpn-client"
# cask openvpn-connect
# cask microsoft-remote-desktop

# Messangers
# cask "slack"
# cask "microsoft-teams"
cask "discord"
cask "whatsapp"
# cask "messenger"
# cask "signal"
# cask zoom

# Terminal & IDE
cask "iterm2"
cask "visual-studio-code"
cask "font-fira-code"
cask "powershell"

# Media & Gaming
cask "spotify"
# cask sony-ps-remote-play
# cask steam

# Containers
cask "docker"

# Genral Tooling
cask "keepingyouawake"
cask "postman"
# cask "the-unarchiver"
# cask google-chrome
# cask nordpass

# vscode --install-extension
vscode "amazonwebservices.amazon-q-vscode"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "antfu.icons-carbon"
vscode "dbaeumer.vscode-eslint"
vscode "dracula-theme.theme-dracula"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "eriklynd.json-tools"
vscode "esbenp.prettier-vscode"
vscode "golang.go"
vscode "ivory-lab.jenkinsfile-support"
vscode "miguelsolorio.fluent-icons"
vscode "mongodb.mongodb-vscode"
vscode "ms-azure-devops.azure-pipelines"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "njpwerner.autodocstring"
vscode "pkief.material-icon-theme"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
vscode "tim-koehler.helm-intellisense"
vscode "yzhang.markdown-all-in-one"
vscode "streetsidesoftware.code-spell-checker"
