---
- name: Playbook for macOS
  hosts: localhost
  vars:
    # User specific variables
    user_group: staff
    git_username: donovan-said
    git_email: donovan.s.said@gmail.com
  vars_files:
    - './vars/azure.yml'
    - './vars/brew.yml'
    - './vars/ruby.yml'
    - './vars/zsh.yml'
  roles:
    - brew
    - azure_cli
    # - ruby
    - git
    - zsh
    - vscode
