---
- hosts: localhost
  connection: local
  vars_files:
    - "./vars/general.yml"
    - "./vars/brew.yml"
    - "./vars/python.yml"
    - "./vars/npm.yml"
  roles:
    - brew
#    - git
#    - zsh
#    - azure_cli