---
- name: Playbook for configuring Mac
  hosts: localhost
  vars_files:
    - "./vars/azure.yml"
    - "./vars/general.yml"
    - "./vars/git.yml"
    - "./vars/brew.yml"
    - "./vars/ruby.yml"
    - "./vars/vscode.yml"
    - "./vars/zsh.yml"
  roles:
    - azure_cli
    - brew
    - ruby
    - git
    - zsh
    - vscode
