---
- hosts: localhost
  connection: local
  vars_files:
    - "./vars/azure.yml"
    - "./vars/general.yml"
    - "./vars/brew.yml"
    - "./vars/ruby.yml"
    - "./vars/vscode.yml"
  roles:
    - azure_cli
    - brew
    - ruby
    - git
    - zsh
    - vscode
