---
- name: Copy .zshrc to user home directory
  ansible.builtin.template:
    src: "{{ role_path }}/templates/.zshrc.j2"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.zshrc"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "{{ user_group }}"
...
