---
# Homebrew is installed via the root bootstrap.sh script, as it is required to
# install Ansible.

- name: Homebrew Check
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Homebrew Fail When Not Installed
  ansible.builtin.fail:
    msg: Homebrew is missing...Install from http://brew.sh/
  when: not homebrew_check.stat.exists

- name: Homebrew Update
  community.general.homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Install Homebrew Cask Packages
  community.general.homebrew_cask:
    name: '{{ brew_cask_packages }}'
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists

- name: Install Homebrew Packages
  community.general.homebrew:
    name: '{{ brew_packages }}'
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
