---
# Homebrew is installed via the root bootstrap.sh script, as it is required to
# install Ansible.

- name: Homebrew Check
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Homebrew Fail When Not Installed
  ansible.builtin.fail:
    msg: Homebrew is missing...Install from http://brew.sh/
  when: not homebrew_check.stat.exists

- name: Homebrew Update
  community.general.homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists

- name: Install Brew Formulae, Casks, and VSCode Extensions from Brewfile.
  ansible.builtin.command:
    brew bundle --file={{ homebrew_brewfile }} --force cleanup
  # https://ansible.readthedocs.io/projects/lint/rules/no-changed-when/
  changed_when: true
